# Generated by Django 4.0.1 on 2022-01-29 04:51

import django.core.serializers.json
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_custom_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="IterationReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("iteration_name", models.CharField(max_length=500)),
                ("iteration_data", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "iteration_reports",
            },
        ),
    ]
